### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stijnb1234** [cakenggt/Quidditch#1]
Dear @cakenggt,

I found this project. It looks great, and want to use it for my private Minecraft server.

I need to update it to 1.12.2, and change it to another language.

Since you have no License on this project, I cannot use it right now.

Could you give me permission to modify and use the code? I will leave your name at the authors.

Thanks in advance!

Kind regards,

Stijn

**Comment by cakenggt** [comment]
Fixed by https://github.com/cakenggt/Quidditch/pull/2 I hope you enjoy the code!
